FROM rockylinux:latest
RUN yum install -y java-1.8.0-openjdk wget && yum update -y && yum clean all
COPY *-all.jar agent.jar
ENTRYPOINT ["java"]
CMD ["-XX:+UnlockExperimentalVMOptions","-Djava.net.preferIPv4Stack=true","-XX:+UseCGroupMemoryLimitForHeap","-XshowSettings:vm","-Djava.security.egd=file:/dev/./urandom","-jar","/agent.jar"]